# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8a3e2cc3513fc8237dea0938d02bd345a574f5b09533700c08fb2c090e095d25c3ad6dc98392ec4e2534fd2395c274db4b0a8ab1b8e741149bf8ee6e8f33cbf8

test:
  secret_key_base: 39cf3bf9c39ab00c4a3f040d655f2623fa217854108cff3e370fc08cc148ab770917619e5ed9efa48aec56690c160cd9de3106c5ad21430f21584346bef0fee4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
